# web01-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web01
  template:
    metadata:
      labels:
        app: web01
    spec:
      containers:
        - name: web01
          image: saurabhshinder43/web01:v1
          ports:
            - containerPort: 80

---

# web01-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: web01-service
spec:
  selector:
    app: web01
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
